<?php $__env->startSection('title'); ?>
<title>BGOC Outdoor System - Client Company</title>
<?php $__env->stopSection(); ?>
<?php $__env->startSection('content'); ?>
<head>
<style>
    .modal {
        display: none;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.5);
        z-index: 9999;
        overflow: auto;
    }
    .modal.show {
        display: block;
    }
    .modal__content {
        background: white;
        margin: 5% auto;
        padding: 0;
        border-radius: 8px;
        max-width: 600px;
        width: 90%;
    }
</style>
<?php echo app('Illuminate\Foundation\Vite')(['resources/css/app.css', 'resources/js/app.js']); ?> <!-- If using Vite -->
</head>
<div class="intro-y flex flex-col sm:flex-row items-center mt-8">
    <h2 class="text-lg font-medium mr-auto">
        Clients
    </h2>
</div>


<!-- filter and datatable -->
<div class="intro-y box p-5 mt-5">
    <div class="pos col-span-12 lg:col-span-4">
        <!-- BEGIN: Client Company -->
        <div>
            <!-- BEGIN: Filter & Add Client Company -->
            <div class="flex flex-col sm:flex-row sm:items-end xl:items-start">
                <!-- BEGIN: Filter -->
                <form class="xl:flex sm:mr-auto">
                    <!-- <div class="sm:flex items-center sm:mr-4">
                        <label class="w-12 flex-none xl:w-auto xl:flex-initial mr-2">Company Status</label>
                        <select class="input w-full sm:w-32 xxl:w-full mt-2 sm:mt-0 sm:w-auto border" id="inputContractStatus">
                            <option value="all">All</option>
                            <option value="1">Active</option>
                            <option value="0">Inactive</option>
                        </select>
                    </div>
                    <div class="mt-2 xl:mt-0">
                        <button type="button" class="button w-full sm:w-16 bg-theme-32 text-white" id="filterClientCompanyButton">Filter</button>
                    </div> -->
                </form>
                <!-- END: Filter -->

                <!-- BEGIN: Add Client Company -->
                <div class="text-center">
                    <a href="javascript:;" data-toggle="modal" data-target="#clientCompanyAddModal" class="button w-50 mr-2 mb-2 flex items-center justify-center bg-theme-32 text-white">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus w-4 h-4">
                            <line x1="12" y1="5" x2="12" y2="19"></line>
                            <line x1="5" y1="12" x2="19" y2="12"></line>
                        </svg>
                        Add New Client
                    </a>
                </div>
                <!-- END: Add Client Company -->
            </div>
            <!-- END: Filter & Add Client Company -->

            <!-- BEGIN: Client Company List -->
            <div class="overflow-x-auto">
                <table id="client_company_table" class="min-w-full border-collapse border border-neutral-300"> <!-- Add border classes to the table -->
                    <thead class="bg-neutral-50 sticky top-0 z-10">
                        <tr class="border-b border-neutral-300">
                            <th class="px-4 py-4 table-header border-r border-neutral-300">PIC</th> <!-- for details-control -->
                            <th class="px-4 py-4 table-header border-r border-neutral-300">No</th>
                            <th class="px-4 py-4 table-header min-w-[350px] border-r border-neutral-300">Client Name</th>
                            <th class="px-4 py-4 table-header min-w-[350px] border-r border-neutral-300">Address</th>
                            <th class="px-4 py-4 table-header min-w-[100px] border-r border-neutral-300">Phone No.</th>
                            <th class="px-4 py-4 table-header min-w-[100px] dt-exclude-export dt-no-sort">Actions</th>
                        </tr>
                    </thead>
                    <tbody id="billboard_tbody" class="bg-white divide-y divide-neutral-200"> <!-- 'divide-y' adds borders between rows -->
                        <!-- DataTables will populate this body with <tr> elements -->
                        <!-- Each <tr> generated by DataTables should ideally have borders applied -->
                        <!-- You can modify the DataTables column definitions to add borders to cells if needed -->
                    </tbody>
                </table>
            </div>
            <!-- END: Client Company List -->
        </div>
        <!-- END: Client Company -->
    </div>
</div>

<!-- BEGIN: Client Company Add Modal -->
<div class="modal" id="clientCompanyAddModal">
    <div class="modal__content">
        <div class="flex items-center px-5 py-5 sm:py-3 border-b border-gray-200 dark:border-dark-5">
            <h2 class="font-medium text-base mr-auto">Add Clients</h2>
        </div>
        <form>
            <div class="p-5 grid grid-cols-12 gap-4 gap-y-3">
                <div class="col-span-12 sm:col-span-12">
                    <label>Client Name <span style="color: red;">*</span></label>
                    <input type="text" class="input w-full border mt-2 flex-1" placeholder="Client Name" id="clientCompanyAddName" required>
                </div>
                <div class="col-span-12 sm:col-span-12">
                    <label>Client Address</label>
                    <input type="text" class="input w-full border mt-2 flex-1" placeholder="Client Address" id="clientCompanyAddAddress">
                </div>
                <div class="col-span-12 sm:col-span-12">
                    <label>Phone No.</label>
                    <input type="text" class="input w-full border mt-2 flex-1" placeholder="Phone No." id="clientCompanyAddPhone">
                </div>
            </div>
            <div class="flex items-center px-5 py-5 sm:py-3 border-b border-gray-200 dark:border-dark-5">
                <h2 class="font-medium text-base mr-auto">Add PIC</h2>
            </div>
            <div id="picContainer">
                <div class="pic">
                    <div class="p-5 grid grid-cols-12 gap-4 gap-y-3">
                        <div class="col-span-12 sm:col-span-12">
                            <label>Name</label>
                            <input type="text" class="input w-full border mt-2" placeholder="Name" name="pic_names[]" required>
                        </div>
                        <div class="col-span-12 sm:col-span-12">
                            <label>Email</label>
                            <input type="text" class="input w-full border mt-2" placeholder="Email" name="pic_emails[]">
                        </div>
                        <div class="col-span-12 sm:col-span-12">
                            <label>Phone No.</label>
                            <input type="text" class="input w-full border mt-2" placeholder="Phone No." name="pic_phones[]">
                        </div>
                        <div class="col-span-12 sm:col-span-12">
                            <label>Designation</label>
                            <div class="flex items-center mt-2">
                                <input type="text" class="input w-full border" placeholder="Designation" name="pic_designations[]">
                            </div>
                        </div>
                        <div class="col-span-12 sm:col-span-12">
                            <div class="flex items-center mt-2">
                                <a href="javascript:void(0);" class="button bg-theme-6 text-white " onclick="removePIC(this)">
                                    Remove
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="px-5 py-3 text-right border-t border-gray-200 dark:border-dark-5">
                <button type="button" onclick="picAdd()" class="button w-20 bg-theme-1 text-white mt-2">Add PIC</button>
                <button type="submit" class="button w-20 bg-theme-1 text-white" id="addClientCompany">Submit</button>
            </div>
        </form>
    </div>
</div>
<!-- END: Client Company Add Modal -->

<!-- BEGIN: Client Company Edit Modal -->
<div class="modal" id="clientCompanyEditModal">
    <div class="modal__content">
        <div class="flex items-center px-5 py-5 sm:py-3 border-b border-gray-200 dark:border-dark-5">
            <h2 class="font-medium text-base mr-auto">Edit Clients</h2>
        </div>
        <form id="clientCompanyEditForm">
            <div class="p-5 grid grid-cols-12 gap-4 gap-y-3">
                <div class="col-span-12 sm:col-span-12">
                    <label>Client Name <span style="color: red;">*</span></label>
                    <input type="text" class="input w-full border mt-2 flex-1" placeholder="Client Name" id="clientCompanyEditName" required>
                </div>
                <div class="col-span-12 sm:col-span-12">
                    <label>Client Address</label>
                    <input type="text" class="input w-full border mt-2 flex-1" placeholder="Client Address" id="clientCompanyEditAddress">
                </div>
                <div class="col-span-12 sm:col-span-12">
                    <label>Phone No.</label>
                    <input type="text" class="input w-full border mt-2 flex-1" placeholder="Phone No." id="clientCompanyEditPhone">
                </div>
            </div>
            <div class="px-5 py-3 text-right border-t border-gray-200 dark:border-dark-5">
                <button type="submit" class="button w-20 bg-theme-1 text-white" id="clientCompanyEditButton">Submit</button>
            </div>
        </form>
    </div>
</div>
<!-- END: Client Company Edit Modal -->

<!-- BEGIN: Client Company Delete Modal -->
<div class="modal" id="clientCompanyDeleteModal">
    <div class="modal__content">
        <div class="p-5 text-center"> <i data-feather="x-circle" class="w-16 h-16 text-theme-6 mx-auto mt-3"></i>
            <div class="text-3xl mt-5">Are you sure?</div>
            <div class="text-gray-600 mt-2">Confirm deleting the client company? This process cannot be undone.</div>
        </div>
        <div class="px-5 pb-8 text-center">
            <button type="button" data-dismiss="modal" class="button w-24 border text-gray-700 dark:border-dark-5 dark:text-gray-300 mr-1">Cancel</button>
            <button type="button" class="button w-24 bg-theme-6 text-white" id="clientCompanyDeleteButton">Delete</button>
        </div>
    </div>
</div>
<!-- END: Client Company Delete Modal -->




<!-- BEGIN: PIC Add Modal -->
<div class="modal" id="picAddModal">
    <div class="modal__content">
        <div class="flex items-center px-5 py-5 sm:py-3 border-b border-gray-200 dark:border-dark-5">
            <h2 class="font-medium text-base mr-auto">Add PIC</h2>
        </div>
        <form>
        <?php echo csrf_field(); ?>
        <input type="hidden" id="picAddCompanyId"> <!-- hidden field for company ID -->
            <div class="p-5 grid grid-cols-12 gap-4 gap-y-3">
                <div class="col-span-12 sm:col-span-12">
                    <label>Designation</label>
                    <input type="text"  title="Please enter client designation" placeholder="Enter a Designation" class="input w-full border mt-2 flex-1" id="picAddDesignation" required>
                </div>
                <div class="col-span-12 sm:col-span-12">
                    <label>Client Name <span style="color: red;">*</span></label>
                    <input type="text" placeholder="Enter a Client Name" class="input w-full border mt-2 flex-1" id="picAddName" required>
                </div>
                <div class="col-span-12 sm:col-span-12">
                    <label>Email</label>
                    <input type="text" placeholder="Enter a Client Email" class="input w-full border mt-2 flex-1" id="picAddEmail" required>
                </div>
                <div class="col-span-12 sm:col-span-12">
                    <label>Contact No.</label>
                    <input type="text"  title="Please enter contact number in correct format" placeholder="Enter a Contact Number" class="input w-full border mt-2 flex-1" id="picAddContact" required>
                </div>
            </div>
            <div class="px-5 py-3 text-right border-t border-gray-200 dark:border-dark-5">
                <button type="submit" class="button w-50 bg-theme-1 text-white" id="picAddButton">Save Client</button>
            </div>
        </form>
        
    </div>
</div>
<!-- END: PIC Add Modal -->

<!-- BEGIN: PIC Edit Modal -->
<div class="modal" id="picEditModal">
    <div class="modal__content">
        <div class="flex items-center px-5 py-5 sm:py-3 border-b border-gray-200 dark:border-dark-5">
            <h2 class="font-medium text-base mr-auto">Edit PIC</h2>
        </div>
        <form>
            <div class="p-5 grid grid-cols-12 gap-4 gap-y-3">
                <div class="col-span-12 sm:col-span-12">
                    <label>Designation</label>
                    <input type="text" class="input w-full border mt-2 flex-1" placeholder="Designation" id="picEditDesignation" required>
                </div>
                <div class="col-span-12 sm:col-span-12">
                    <label>PIC Name <span style="color: red;">*</span></label>
                    <input type="text" class="input w-full border mt-2 flex-1" placeholder="PIC Name" id="picEditName" required>
                </div>
                <div class="col-span-12 sm:col-span-12">
                    <label>Contact No.</label>
                    <input type="text" class="input w-full border mt-2 flex-1" placeholder="Contact No" id="picEditContact" required>
                </div>
                <div class="col-span-12 sm:col-span-12">
                    <label>Email</label>
                    <input type="email" class="input w-full border mt-2 flex-1" placeholder="Email" id="picEditEmail" required>
                </div>
                
            </div>

            <div class="px-5 py-3 text-right border-t border-gray-200 dark:border-dark-5">
                <button type="submit" class="button w-20 bg-theme-1 text-white" id="picEditButton">Update</button>
            </div>
        </form>
    </div>
</div>
<!-- END: PIC Edit Modal -->

<!-- BEGIN: PIC Delete Modal -->
<div class="modal" id="picDeleteModal">
    <div class="modal__content">
        <div class="p-5 text-center"> <i data-feather="x-circle" class="w-16 h-16 text-theme-6 mx-auto mt-3"></i>
            <div class="text-3xl mt-5">Are you sure?</div>
            <div class="text-gray-600 mt-2">Confirm deleting the PIC? This process cannot be undone.</div>
        </div>
        <div class="px-5 pb-8 text-center">
            <button type="button" data-dismiss="modal" class="button w-24 border text-gray-700 dark:border-dark-5 dark:text-gray-300 mr-1">Cancel</button>
            <button type="button" class="button w-24 bg-theme-6 text-white" id="picDeleteButton">Delete</button>
        </div>
    </div>
</div>
<!-- END: Client Delete Modal -->


<script>

    // Add a new PIC input field
    function picAdd() {
        var picTemplate = `
            <div class="pic">
                <div class="p-5 grid grid-cols-12 gap-4 gap-y-3">
                    <div class="col-span-12 sm:col-span-12">
                        <label>Name</label>
                        <input type="text" class="input w-full border mt-2" placeholder="Name" name="pic_names[]" required>
                    </div>
                    <div class="col-span-12 sm:col-span-12">
                        <label>Email</label>
                        <input type="text" class="input w-full border mt-2" placeholder="Phone No." name="pic_emails[]" required>
                    </div>
                    <div class="col-span-12 sm:col-span-12">
                        <label>Phone No.</label>
                        <input type="text" class="input w-full border mt-2" placeholder="Phone No." name="pic_phones[]" required>
                    </div>
                    <div class="col-span-12 sm:col-span-12">
                        <label>Designation</label>
                        <div class="flex items-center mt-2">
                            <input type="text" class="input w-full border" placeholder="Designation" name="pic_designations[]" required>
                        </div>
                    </div>
                    <div class="col-span-12 sm:col-span-12">
                        <div class="flex items-center mt-2">
                            <a href="javascript:void(0);" class="button bg-theme-6 text-white " onclick="removePIC(this)">
                                Remove
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        `;

        $("#picContainer").append(picTemplate);
    }

    // Remove a pic input field in edit modal
    function removePIC(button) {
        var container = $(button).closest('.pic');
        var inputField = container.find('input');
        var hasData = inputField.val();

        console.log("data:", inputField);

        // Remove the subcategory field
        container.remove();

        // If it had existing data, remove it from the modal
        if (hasData) {
            inputField.remove();
        }
    }

    $(document).ready(function() {
        // Global variables
        var filterClientCompanyStatus = null;
        let originalCompanyId = null;
        var lastClickedLink;

        // Listen to below buttons
        // document.getElementById("filterClientCompanyButton").addEventListener("click", filterClientCompanyButton);
        document.getElementById("addClientCompany").addEventListener("click", addClientCompany);
        document.getElementById("clientCompanyDeleteButton").addEventListener("click", clientCompanyDeleteButton);

        // When "filterClientCompanyButton" button is clicked, initiate initClientCompanyDatatable
        // function filterClientCompanyButton() {
        //     filterClientCompanyStatus = document.getElementById("inputContractStatus").value;
        //     initClientCompanyDatatable();
        // };

        // When page first loads, load table
        // filterClientCompanyButton();

        // When any submit button is clicked
        // (function () {
        //     document.getElementById('addClientCompany').addEventListener('click', e => e.preventDefault());
        //     document.getElementById('clientCompanyEditButton').addEventListener('click', e => {
        //         e.preventDefault();
        //         editClientCompany();
        //     });
        // })();

        // Open modal
        function openAltEditorModal(selector) {
            const modal = document.querySelector(selector);
            if (modal) {
                modal.classList.add('show');
                // Prevent body scroll when modal is open
                document.body.style.overflow = 'hidden';
            }
        }

        function closeAltEditorModal(selector) {
            const modal = document.querySelector(selector);
            if (modal) {
                modal.classList.remove('show');
                // Re-enable body scroll
                document.body.style.overflow = '';
            }
        }

        function initClientCompanyDatatable() {
            console.log("initClientCompanyDatatable() called");
            const dt = new Date();
            const formattedDate = `${dt.getFullYear()}${(dt.getMonth() + 1).toString().padStart(2, '0')}${dt.getDate().toString().padStart(2, '0')}`;
            const formattedTime = `${dt.getHours()}:${dt.getMinutes()}:${dt.getSeconds()}`;
            const $fileName = `Client_Company_List_${formattedDate}_${formattedTime}`;

            const table = $('#client_company_table').DataTable({
                destroy: true,
                processing: true,
                serverSide: true,
                ordering: true,
                order: [[0, 'desc']],
                pageLength: 25,
                ajax: {
                    url: "<?php echo e(route('client-company.list')); ?>",
                    type: "POST",
                    data: function (d) {
                        d._token = $('meta[name="csrf-token"]').attr('content');
                        d.status = filterClientCompanyStatus;
                        return d;
                    },
                    dataSrc: function (json) {
                        return json.data;
                    }
                },
                dom: "lBfrtip",
                buttons: [
                    {
                        extend: "excel",
                        className: "button w-24 rounded-full shadow-md mr-1 mb-2 bg-theme-7 text-white",
                        title: $fileName,
                        exportOptions: { columns: ":not(.dt-exclude-export)" },
                        init: function (api, node) {
                            $(node).removeClass('dt-button buttons-html5');
                        },
                    },
                ],
                columnDefs: [{ targets: 'dt-no-sort', orderable: false }],
                columns: [
                    {
                        className: 'details-control',
                        orderable: false,
                        data: null,
                        defaultContent: '',
                        render: () => '<button class="bg-theme-1 text-white px-2 py-1 rounded">+</button>'
                    },
                    {
                        data: null,
                        name: 'no',
                        orderable: false,
                        searchable: false,
                        render: (data, type, row, meta) => meta.row + meta.settings._iDisplayStart + 1
                    },
                    { data: "name" },
                    { data: "address" },
                    { data: "phone" },
                    {
                        data: "id",
                        render: (data) => `
                            <div class="flex justify-center items-center gap-3">
                                <!-- Edit Icon -->
                                <a href="javascript:;" 
                                class="client-company-edit flex items-center justify-center w-8 h-8 text-theme-9 rounded hover:bg-gray-100" 
                                data-id="${data}" 
                                title="Edit">
                                    <svg xmlns="http://www.w3.org/2000/svg" 
                                        class="w-5 h-5" 
                                        fill="none" 
                                        viewBox="0 0 24 24" 
                                        stroke="currentColor">
                                        <path d="M15.232 5.232l3.536 3.536M9 13h3l9-9a1.5 1.5 0 00-2.121-2.121l-9 9v3z"/>
                                    </svg>
                                </a>

                                <!-- Delete Icon -->
                                <a href="javascript:;" 
                                class="client-company-delete flex items-center justify-center w-8 h-8 text-theme-6 rounded hover:bg-gray-100" 
                                data-id="${data}" 
                                title="Delete">
                                    <svg xmlns="http://www.w3.org/2000/svg" 
                                        class="w-5 h-5" 
                                        fill="none" 
                                        viewBox="0 0 24 24" 
                                        stroke="currentColor">
                                        <polyline points="3 6 5 6 21 6"></polyline>
                                        <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4
                                                a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/>
                                        <line x1="10" y1="11" x2="10" y2="17"></line>
                                        <line x1="14" y1="11" x2="14" y2="17"></line>
                                    </svg>
                                </a>
                            </div>
                        `
                    }


                ],
                initComplete: function () {
                    // Safe styling adjustments (only run after table is built)
                    const dtButtonsDiv = document.querySelector(".dt-buttons");
                    if (dtButtonsDiv) dtButtonsDiv.classList.add("mt-2");

                    const filterDiv = document.getElementById("client_company_table_filter");
                    if (filterDiv) {
                        filterDiv.style.float = "right";
                        filterDiv.classList.remove('dataTables_filter');
                        const inputElement = filterDiv.querySelector("label input");
                        if (inputElement) inputElement.classList.add("input", "border", "mt-2", "ml-2", "mr-1", "mb-5");
                    }

                    const infoDiv = document.getElementById("client_company_table_info");
                    if (infoDiv) {
                        infoDiv.style.float = "left";
                        infoDiv.classList.add("mt-5");
                    }

                    const paginateDiv = document.getElementById("client_company_table_paginate");
                    if (paginateDiv) {
                        paginateDiv.style.float = "right";
                        paginateDiv.classList.add("mt-5");
                    }

                    const existingDiv = document.getElementById("client_company_table_length");
                    if (existingDiv) {
                        existingDiv.classList.remove('dataTables_length');
                        existingDiv.classList.add('mt-2', 'mb-1');
                        const existingSelect = existingDiv.querySelector('select');
                        if (existingSelect) existingSelect.className = 'input sm:w-auto border';
                    }
                }
            });

            // Row expand/collapse for PICs
            $('#client_company_table tbody').off('click', 'td.details-control').on('click', 'td.details-control', function () {
                const tr = $(this).closest('tr');
                const row = table.row(tr);

                if (row.child.isShown()) {
                    row.child.hide();
                    tr.removeClass('shown');
                    $(this).find("button").text("+");
                } else {
                    const companyId = row.data().id;
                    $.ajax({
                        url: "<?php echo e(route('client-company.pics')); ?>",
                        type: "POST",
                        data: {
                            _token: $('meta[name="csrf-token"]').attr('content'),
                            company_id: companyId
                        },
                        success: function (response) {
                            // pass companyId to formatPICs
                            row.child(formatPICs(response.pics, companyId)).show();
                            tr.addClass('shown');
                            $(tr).find("td.details-control button").text("-");
                        }
                    });

                }
            });

            // clientCompanyEditModal();
        }

        function formatPICs(pics, companyId) {
            if (!pics || pics.length === 0) {
                return `
                    <div class="p-2">No PICs available</div>
                    <div class="flex justify-end mb-2 mt-2">
                        <button class="bg-theme-1 text-white px-5 py-1 rounded add-pic-btn" data-company-id="${companyId}">
                            + Add PIC
                        </button>
                    </div>
                `;
            }

            let html = '<table class="table-auto w-full text-sm border mt-2"><div class="ml-3"><strong>PIC</strong></div>';
            html += '<thead><tr><th>Name</th><th>Email</th><th>Phone</th><th>Designation</th><th>Action</th></tr></thead><tbody>';

            pics.forEach(pic => {
                html += `<tr>
                    <td>${pic.name ? pic.name : '-'}</td>
                    <td>${pic.email ? pic.email : '-'}</td>
                    <td>${pic.phone ? pic.phone : '-'}</td>
                    <td>${pic.designation ? pic.designation : '-'}</td>
                    <td>
                        <button class="edit-pic-btn bg-theme-1 text-white px-2 py-1 rounded"
                            data-name="${pic.name}"
                            data-phone="${pic.phone}"
                            data-email="${pic.email}"
                            data-designation="${pic.designation}"
                            data-id="${pic.id}">Edit</button>

                        <button class="delete-pic-btn px-2 py-1 bg-theme-6 text-white rounded"
                            data-id="${pic.id}">Delete</button>
                    </td>
                </tr>`;
            });

            html += '</tbody></table>';

                        // Add button to create new PIC
            html += `
                <div class="flex justify-end mb-2 mt-2">
                    <button class="bg-theme-1 text-white px-5 py-1 rounded add-pic-btn" data-company-id="${companyId}">
                        + Add PIC
                    </button>
                </div>
            `;
            return html;
        }



        // Add New Client Company
        function addClientCompany() {
            let pics = [];
            $('#picContainer .pic').each(function () {
                pics.push({
                    name: $(this).find('input[name="pic_names[]"]').val(),
                    email: $(this).find('input[name="pic_emails[]"]').val(),
                    phone: $(this).find('input[name="pic_phones[]"]').val(),
                    designation: $(this).find('input[name="pic_designations[]"]').val()
                });
            });

            $.ajax({
                type: 'POST',
                url: "<?php echo e(route('client-company.create')); ?>",
                data: {
                    _token: $('meta[name="csrf-token"]').attr('content'),
                    name: $('#clientCompanyAddName').val(),
                    address: $('#clientCompanyAddAddress').val(),
                    companyPhone: $('#clientCompanyAddPhone').val(),
                    pics: pics
                },
                success: function(response) {
                    closeAltEditorModal("#clientCompanyAddModal");
                    window.showSubmitToast("Successfully added.", "#91C714");

                    // Clear form
                    $('#clientCompanyAddModal input').val("");
                    $('#client_company_table').DataTable().ajax.reload();
                },
                error: function(xhr) {
                    let response = JSON.parse(xhr.responseText);
                    window.showSubmitToast("Error: " + response.error, "#D32929");
                }
            });
        }
        

        $(document).off('click', '.client-company-edit').on('click', '.client-company-edit', function() {
            const companyId = $(this).data('id');
            originalCompanyId = companyId;

            const $row = $(this).closest('tr');
            const cells = $row.find('td');

            $('#clientCompanyEditName').val(cells.eq(2).text().trim());
            $('#clientCompanyEditAddress').val(cells.eq(3).text().trim());
            $('#clientCompanyEditPhone').val(cells.eq(4).text().trim());

            openAltEditorModal('#clientCompanyEditModal');
        });

        $('#clientCompanyEditForm').off('submit').on('submit', function(e) {
            e.preventDefault();

            $.ajax({
                type: 'POST',
                url: "<?php echo e(route('client-company.edit')); ?>",
                data: {
                    _token: $('meta[name="csrf-token"]').attr('content'),
                    id: originalCompanyId,
                    name: $('#clientCompanyEditName').val().trim(),
                    address: $('#clientCompanyEditAddress').val().trim(),
                    companyPhone: $('#clientCompanyEditPhone').val().trim()
                },
                success: function(response) {
                    closeAltEditorModal('#clientCompanyEditModal');
                    window.showSubmitToast("Successfully updated.", "#91C714");

                    $('#clientCompanyEditForm')[0].reset();
                    $('#client_company_table').DataTable().ajax.reload(null, false);
                },
                error: function(xhr) {
                    const response = JSON.parse(xhr.responseText);
                    window.showSubmitToast("Error: " + response.error, "#D32929");
                }
            });
        });



        // Store the ID of the last clicked moda when it's triggered
        (function() {
            $(document).on('click', "[data-toggle='modal']", function() {
                lastClickedLink = $(this).attr('id');
            });
        })();

        // Open delete modal and store company id
        $(document).on('click', '.client-company-delete', function() {
            const companyId = $(this).data('id');

            // Store the company ID on the modal itself
            $('#clientCompanyDeleteModal').attr('data-company-id', companyId);

            // Open modal
            openAltEditorModal('#clientCompanyDeleteModal');
        });

        $('#clientCompanyDeleteButton').off('click').on('click', function() {
            const companyId = $('#clientCompanyDeleteModal').attr('data-company-id');

            $.ajax({
                type: 'POST',
                url: "<?php echo e(route('client-company.delete')); ?>",
                data: {
                    _token: $('meta[name="csrf-token"]').attr('content'),
                    id: companyId
                },
                success: function(response) {
                    // Close modal
                    closeAltEditorModal('#clientCompanyDeleteModal');

                    // Show success toast
                    window.showSubmitToast("Successfully deleted.", "#91C714");

                    // Reload table
                    $('#client_company_table').DataTable().ajax.reload();
                },
                error: function(xhr) {
                    const response = JSON.parse(xhr.responseText);
                    window.showSubmitToast("Error: " + response.error, "#D32929");
                }
            });
        });




















        // handle add PIC click button
        $(document).on('click', '.add-pic-btn', function() {
            const companyId = $(this).data('company-id');

            // Clear modal fields
            $('#picAddName').val('');
            $('#picAddContact').val('');
            $('#picAddEmail').val('');
            $('#picAddDesignation').val('');
            $('#picAddCompany').val(companyId);

            // Set company ID in hidden field
            $('#picAddCompanyId').val(companyId);

            openAltEditorModal('#picAddModal');
        });


        $('#picAddButton').off('click').on('click', function(e) {
            e.preventDefault();

            const name = $('#picAddName').val();
            const phone = $('#picAddContact').val();
            const email = $('#picAddEmail').val();
            const designation = $('#picAddDesignation').val();
            const companyId = $('#picAddCompanyId').val(); // now correctly set

            $.ajax({
                url: '/client-company/pic/create', // create this route in Laravel
                type: 'POST',
                data: {
                    _token: $('meta[name="csrf-token"]').attr('content'),
                    company_id: companyId,
                    name: name,
                    phone: phone,
                    email: email,
                    designation: designation
                },
                success: function(response) {
                    closeAltEditorModal('#picAddModal');
                    window.showSubmitToast("Successfully added.", "#91C714");

                    // Clean fields
                    $('#picAddName').val('');
                    $('#picAddContact').val('');
                    $('#picAddEmail').val('');
                    $('#picAddDesignation').val('');

                    // Reload DataTable
                    $('#client_company_table').DataTable().ajax.reload();
                },
                error: function(xhr) {
                    let response = JSON.parse(xhr.responseText);
                    window.showSubmitToast("Error: " + response.error, "#D32929");
                }
            });
        });



        // Handle PIC Edit button click
        $('#client_company_table tbody').off('click', '.edit-pic-btn').on('click', '.edit-pic-btn', function () {
            const btn = $(this);
            const picId = btn.data('id');
            const name = btn.data('name');
            const phone = btn.data('phone');
            const email = btn.data('email');
            const designation = btn.data('designation');

            // Fill modal fields
            $('#picEditName').val(name);
            $('#picEditContact').val(phone);
            $('#picEditEmail').val(email);
            $('#picEditDesignation').val(designation);

            // Store PIC ID directly on modal element
            $('#picEditModal').attr('data-pic-id', picId);

            var element = "#picEditModal";
            openAltEditorModal(element);
        });

        $('#picEditButton').off('click').on('click', function (e) {
            e.preventDefault();
            const picId = $('#picEditModal').attr('data-pic-id');
            const name = $('#picEditName').val();
            const phone = $('#picEditContact').val();
            const email = $('#picEditEmail').val();
            const designation = $('#picEditDesignation').val();

            $.ajax({
                url: '/client-company/pic/update', // create this route in Laravel
                type: 'POST',
                data: {
                    _token: $('meta[name="csrf-token"]').attr('content'),
                    id: picId,
                    name: name,
                    phone: phone,
                    email: email,
                    designation: designation
                },
                success: function(response) {
                    // Close modal after successfully edited
                    var element = "#picEditModal";
                    closeAltEditorModal(element);

                    // Show successful toast
                    window.showSubmitToast("Successfully updated.", "#91C714");

                    // Clean fields
                    document.getElementById("picEditName").value = "";
                    document.getElementById("picEditContact").value = "";
                    document.getElementById("picEditEmail").value = "";
                    document.getElementById("picEditDesignation").value = "";

                    // Reload table
                    $('#client_company_table').DataTable().ajax.reload();
                },
                error: function(xhr, status, error) {
                    // Display the validation error message
                    var response = JSON.parse(xhr.responseText);
                    var error = "Error: " + response.error;

                    // Show fail toast
                    window.showSubmitToast(error, "#D32929");
                }
            });
        });

        // Handle PIC Delete button click
        let lastClickedPicId = null;

        $('#client_company_table tbody').off('click', '.delete-pic-btn').on('click', '.delete-pic-btn', function () {
            lastClickedPicId = $(this).data('id');

            // Show delete confirmation modal
            var element = "#picDeleteModal";
            openAltEditorModal(element);
        });

        $('#picDeleteButton').off('click').on('click', function () {
            if (!lastClickedPicId) return;

            $.ajax({
                type: 'POST',
                url: '/client-company/pic/delete', // create this route in Laravel
                data: {
                    _token: $('meta[name="csrf-token"]').attr('content'),
                    id: lastClickedPicId,
                },
                success: function (response) {
                    // Close modal after successfully deleted
                    var element = "#picDeleteModal";
                    closeAltEditorModal(element);

                    // Show successful toast
                    window.showSubmitToast("PIC deleted successfully.", "#91C714");

                    // Reload table
                    $('#client_company_table').DataTable().ajax.reload();
                },
                error: function (xhr, status, error) {
                    var response = JSON.parse(xhr.responseText);
                    var errorMsg = "Error: " + response.error;

                    // Show fail toast
                    window.showSubmitToast(errorMsg, "#D32929");
                }
            });
        });



    
        initClientCompanyDatatable();
    });
</script>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH D:\Projects\Laravel\KL_tracker\resources\views\client_company\index.blade.php ENDPATH**/ ?>